### ISSUE TITLE
sensors exited with code 1

### ISSUE THREAD

**Issue by thetbw** [ocristopfer/cockpit-sensors-old#10]
![image](https://user-images.githubusercontent.com/31307256/190307656-e1769f8c-d120-4bb5-ad43-5ecab86948ae.png)

system: Ubuntu 16.04.7 LTS x86 version
cpu: Atom d525

**Comment by ocristopfer** [comment]
Hello.
Did you install the lm-sensor and run the sensor detection command?
It is possible that it is a problem in the installation of the lm-sensor.
Check if the command "sensors" work on terminal

**Comment by thetbw** [comment]
![image](https://user-images.githubusercontent.com/31307256/190535460-c30f3833-7558-4b23-baa9-273d1641d783.png)
it works
Where can I find logs

**Comment by ocristopfer** [comment]
I managed to fix it, just install the latest version.
I updated the readme script
