### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AnterCreeper** [ocristopfer/cockpit-sensors-old#18]
A adapter with plenty of temperature and voltage. So a label is needed and get from the lm-sensor is ok.

**Comment by ocristopfer** [comment]
Sorry, but I did not understand.

**Comment by AnterCreeper** [comment]
example 1:
![image](https://user-images.githubusercontent.com/30188772/200315392-2b5c2489-f98c-4d54-81f4-0baa4d1a6190.png)

a lot of voltage, but I don't know its name😥

**Comment by AnterCreeper** [comment]
example 2:
![image](https://user-images.githubusercontent.com/30188772/200315627-8e383a45-10fe-4002-8465-362d5d043770.png)
a lot of drivetemp, but i don't know which drive is it.

**Comment by AnterCreeper** [comment]
So for example 1, a name read from sensors is needed.
for example 2, add a configure file which contains friendly names to replace the chip names(for example, w83795adg-i2c-1-2f can be renamed as "BIOS", drivetemp-scsi-0-0 can be renamed as "TOSHIBA HTS721010A9E630").

**Comment by AnterCreeper** [comment]
In my opinion, for example 2, it should be done by lm-sensor, and I comment at https://github.com/lm-sensors/lm-sensors/issues/417

**Comment by ocristopfer** [comment]
this modification need by maid by the lm-sensors. i can try something.

**Comment by ocristopfer** [comment]
![image](https://user-images.githubusercontent.com/4951630/204074728-75f0ee1b-24a5-40fa-9a53-c363a1d9ea7b.png)
I added a label that shows some more information from the sensors.

**Comment by ocristopfer** [comment]
One thing you can do is manually define the name of the sensors in lm-sensors and the result will be reflected in the plugin

**Comment by ocristopfer** [comment]
The modification I reported before is in the latest version (1.2)

**Comment by ocristopfer** [comment]
you can try to change the name of the sensors by looking at this documentation: https://wiki.archlinux.org/title/lm_sensors

**Comment by AnterCreeper** [comment]
thanks!
