### ISSUE TITLE
Unknown compression when installing latest version

### ISSUE THREAD

**Issue by breadtf** [ocristopfer/cockpit-sensors-old#32]
Both DPKG and APT return the error:
`dpkg-deb: error: archive '/home/bread/cockpit-sensors.deb' uses unknown compression for member 'control.tar.zst', giving up`
This was not a problem in older versions, only the latest version has this error.

**Comment by ocristopfer** [comment]
What version of linux are you using?
I tested it on ubuntu 22.04 and it worked correctly.
![Captura de tela de 2023-03-22 07-40-56](https://user-images.githubusercontent.com/4951630/226878649-ff4c3b70-95c0-4e1a-8b3b-ded3c34cf962.png)

**Comment by AnterCreeper** [comment]
The answer is, Debian refused to support zstd compression right now, at least need to wait for a long time.

**Comment by AnterCreeper** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664

**Comment by AnterCreeper** [comment]
https://wiki.debian.org/Teams/Dpkg/FAQ#Q:_Can_we_add_support_for_new_compressors_for_.deb_packages.3F

**Comment by AnterCreeper** [comment]
So maybe only should use zstd in the Ubuntu.

Here I provided some information while facing the same issue. Method below:
1. rename to the .zip
2. unzip
3. zstd decompress and re-organized them
put control data in ./DEBIAN, other in the ./
4. repackaged them using dpkg-deb -b ./ ../**.deb

**Comment by ocristopfer** [comment]
i gone test on debian.

**Comment by AnterCreeper** [comment]
👍️
