### ISSUE TITLE
Failing to read from the index.js

### ISSUE THREAD

**Issue by Ejz9** [ocristopfer/cockpit-sensors-old#34]
The sensors page doesn't load. It says whoops in the top right and that says to CTRL+SHIFT+J to view the JS log and this is what prints out:
index.js:2 TypeError: Cannot read properties of undefined (reading 'includes')
    at Qt.setIcon (index.js:2:206872)
    at index.js:2:210568
    at Array.map (<anonymous>)
    at index.js:2:210115
    at Array.map (<anonymous>)
    at Qt.render (index.js:2:209937)
    at Xo (index.js:2:93308)
    at Vo (index.js:2:93107)
    at qi (index.js:2:133938)
    at Ms (index.js:2:120160)
ci @ index.js:2
index.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at Qt.setIcon (index.js:2:206872)
    at index.js:2:210568
    at Array.map (<anonymous>)
    at index.js:2:210115
    at Array.map (<anonymous>)
    at Qt.render (index.js:2:209937)
    at Xo (index.js:2:93308)
    at Vo (index.js:2:93107)
    at qi (index.js:2:133938)
    at Ms (index.js:2:120160)

**Comment by ocristopfer** [comment]
Sorry for the delay in responding, I've been very busy with my work, but I made a correction to the code that might solve your problem.

**Comment by ocristopfer** [comment]
please test this version.
https://github.com/ocristopfer/cockpit-sensors/releases/tag/v1.4.2

**Comment by Ejz9** [comment]
Hi, I am also delayed! I am unable to get the install script for cockpit-sensors to install though as it gives me an error 404 when attempting to talk to git to retrieve it or something similar to that...

*Edit
I've noticed this is probably to do with the link the wget attempts to access as when you run this in a web browser it resolves a 404 error. Hope this info helps!

**Comment by naruyan** [comment]
It looks like the new version still has the same issues as typeof returns a string not a value, I've submitted PR #39 that should fix that and it is now working fully for me.

For reference, this seems to only happen when sensors returns a sensor value of N/A.

**Comment by ocristopfer** [comment]
fix of @naruyan  add to relase 1.4.2
