### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by mikeyo** [ocristopfer/cockpit-sensors-old#47]
I installed latest sensors plugin in cockpit but my layout is not easy to read.
I only have one HID device reported by lmsensors (I am passing through corsair USB PSU to a VM) which is normal. Is there a way to change the background to black to match the rest of the cockpit theme?
![image](https://github.com/ocristopfer/cockpit-sensors/assets/11810828/bee6f752-71ec-4edf-a883-c1649a065dad)

**Comment by ocristopfer** [comment]
What is your version of the cockpit?
because the last time I changed the layout it was working according to the chosen theme.

**Comment by mikeyo** [comment]
> What is your version of the cockpit? because the last time I changed the layout it was working according to the chosen theme.

Here is my version...

![image](https://github.com/ocristopfer/cockpit-sensors/assets/11810828/fe6554ef-215a-4108-99f7-be7d52611000)

**Comment by mikeyo** [comment]
> > What is your version of the cockpit? because the last time I changed the layout it was working according to the chosen theme.
> 
> Here is my version...
> 
> ![image](https://private-user-images.githubusercontent.com/11810828/294169392-fe6554ef-215a-4108-99f7-be7d52611000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Nzc0NDIsIm5iZiI6MTcwNDk3NzE0MiwicGF0aCI6Ii8xMTgxMDgyOC8yOTQxNjkzOTItZmU2NTU0ZWYtMjE1YS00MTA4LTk5ZjctYmU3ZDUyNjExMDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDEyNDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZGQwNDU2ZGFmYmIwOTE1YzkxZmZjODNjNjg4YzE4NDhkMTkwYTk0YzI3ZjY1ODEzYjEyYjhiY2Q0YWNkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LOt27KIzrGIwFeY0C53T8hHfNBj_0v_7-bN7xAlBmS4)

@ocristopfer any thoughts on what could be wrong please?

**Comment by ocristopfer** [comment]
sorry for the delay,  gone check thats

**Comment by mikeyo** [comment]
> sorry for the delay, gone check thats

Any update?

**Comment by ocristopfer** [comment]
https://github.com/ocristopfer/cockpit-sensors

The problem with the layout is the update off planterfly.
I'm trying to make a new repo using a Start Kit fork to solve these update problems

**Comment by ocristopfer** [comment]
I archived the old repository and made a new one with the cockpit start kit fork, to avoid compatibility problems after updates
The fix for the problem highlighted is in the repository https://github.com/ocristopfer/cockpit-sensors
