### ISSUE TITLE
Request to hide cards that have invalid values (0)

### ISSUE THREAD

**Issue by brikim** [ocristopfer/cockpit-sensors-old#48]
![SensorsTemps](https://github.com/ocristopfer/cockpit-sensors/assets/3686683/0090203b-5d27-43ee-a128-fe56bfa6bb00)

It would be great to have an option to hide cards that have invalid temperatures. Thanks awesome plugin!

**Comment by ocristopfer** [comment]
i gona try

**Comment by ocristopfer** [comment]
I archived the old repository and made a new one with the cockpit start kit fork, to avoid compatibility problems after updates
The fix for the problem highlighted is in the repository https://github.com/ocristopfer/cockpit-sensors
